#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/easyhour/Projects/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/easyhour/Projects/easyhour_app"
export "FLUTTER_TARGET=/Users/easyhour/Projects/easyhour_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/easyhour/Projects/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=2.0.4"
export "FLUTTER_BUILD_NUMBER=1002004"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
